import type { NextPage } from 'next'
import { Fragment } from 'react'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <Fragment>
      <Head>
        <title>Tree DND</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <main></main>
    </Fragment>
  )
}

export default Home
